# AI Detector

# Today's challenge is inspired by the release of ChatGPT on November 30, 2022.

# Given a string of one or more sentences, determine if it was likely generated by AI using the following rules:

#     It contains two or more dashes (-).

#     It contains two or more sets of parenthesis (()). Text can be within the parenthesis.

#     It contains three or more words with 7 or more letters.

#     Words are separated by a single space and only consist of letters (A-Z). Don't include punctuation or other non-letters as part of a word.

# If the given sentence meets any of the rules above, return "AI", otherwise, return "Human".
# Tests

# 1. detect_ai("The quick brown fox jumped over the lazy dog.") should return "Human".
# 2. detect_ai("The hypersonic brown fox - jumped (over) the lazy dog.") should return "Human".
# 3. detect_ai("Yes - you're right! I made a mistake there - let me try again.") should return "AI".
# 4. detect_ai("The extraordinary students were studying vivaciously.") should return "AI".
# 5. detect_ai("The (excited) student was (coding) in the library.") should return "AI".

def detect_ai(text):
    # Rule 1: Check for two or more dashes
    if text.count('-') >= 2:
        return "AI"

    # Rule 2: Check for two or more sets of parenthesis
    if text.count('(') >= 2 and text.count(')') >= 2:
        return "AI"

    # Rule 3: Check for three or more words with 7 or more letters
    words = text.split()
    if len(words) >= 3:
        long_words = [word for word in words if len(''.join(filter(str.isalpha, word))) >= 7]
        if len(long_words) >= 3:
            return "AI"

    # Default to "Human"
    return "Human"

print(detect_ai("The quick brown fox jumped over the lazy dog."))  # should return "Human"
print(detect_ai("The hypersonic brown fox - jumped (over) the lazy dog."))  # should return "Human"
print(detect_ai("Yes - you're right! I made a mistake there - let me try again."))  # should return "AI"
print(detect_ai("The extraordinary students were studying vivaciously."))  # should return "AI"
print(detect_ai("The (excited) student was (coding) in the library."))  # should return "AI"

# Comments: straightforward exercise. Basically checking three rules, only the third one being a bit more difficult to implement